### ISSUE TITLE
How to handle optional features in Specifications

### ISSUE THREAD

**Issue by paulbuck** [jakartaee/specification-committee#54]
General discussions occurred at previous Spec Committee calls:
From [July 14th, 2021](https://jakarta.ee/meeting_minutes/specification_committee/minutes-specification-july-14-2021.pdf) - For background see proposal from Dan, Kevin & Scott

For Jakarta EE 10 a resolution was passed:
From [August 25th, 2021](https://jakarta.ee/meeting_minutes/specification_committee/minutes-specification-august-25-2021.pdf)  - See ballot results for the “RESOLUTION: The Jakarta EE Specification Committee resolves that no new optional features may be added in Jakarta EE 10 and beyond in component, Platform, or Profile specifications.

**Comment by paulbuck** [comment]
1. An individual specification can have optional features, however when a component specification is included in the Platform an optional feature must be declared required (or included), or it is not included. This requirement to be noted in the Platform specification.
2. Also note, in Jakarta EE 10, the Platform project's intention was to remove all the then existing optional features. This was apparently not reflected in the EE 10 Platform specification.
If 1. is adopted, 2. is no longer needed. The guidance in the 08/25/21 resolution would need to be revised to include optional features in component specifications. 
There are impacts to compatibility that need to be carefully considered.
Discussion to be continued.

**Comment by dblevins** [comment]
Item to add to the discussion, in the Core Profile specification there is a section dedicated to specifications which are optional and features of specifications which are optional.

 - https://jakarta.ee/specifications/coreprofile/10/jakarta-coreprofile-spec-10.0.html#optional-components

This seems to contradict the August 25th, 2021 resolution.  That section uses the word optional and also uses words from the dictionary definition of optional, which is "left to one's choice; [not required](https://www.dictionary.com/browse/optional) or mandatory:"

**Comment by paulbuck** [comment]
Revise 1. to .... "An individual specification can have optional features, however when a component specification is included in the Platform **Web and Core Profiles** an optional feature must be declared required (or included), or it is not included. This requirement to be noted in the Platform specification." and consider putting forward as a resolution to vote on.

**Comment by paulbuck** [comment]
Draft resolution to be voted on the 02/08/23 call: "An individual specification can have optional features, however when a component specification is included in the **Platform and Web Profile, and Core Profile** an optional feature must be explicitly declared as required, otherwise it is not required. This requirement to be noted in the Platform specification."

**Comment by edburns** [comment]
@ivargrimstad  can you please add label jea-linked to this issue? I'd like to be able to add labels, but I cannot. Linked to AB#101

**Comment by edburns** [comment]
This really should be closed, right?
