### ISSUE TITLE
Requirements on standalone TCKs

### ISSUE THREAD

**Issue by Emily-Jiang** [jakartaee/specification-committee#59]
It is not clear that the specification committee has discussed and decided on the requirements for individual specification TCK execution (aka standalone TCK).  Recent discussions about individual specification TCKs have identified an exposure for a platform implementation to claim compliance for individual specifications that are included in the platform, web profile or core profile.  A TCK must be executable within the context of the profile it is included in: platform, web profile or core profile.  ​Otherwise, there is no confirmation that the compliant platform, web profile or core profile implementation functions properly with respect to the individual specification TCK.

Some individual specification TCK teams have indicated the desire to develop TCKs that are only executable outside of a profile implementation and only run directly on Java SE.  It is acceptable for specification projects to develop a TCK that can run directly on Java SE.  It is not acceptable for that complete TCK to only be executable directly on Java SE.

A TCK can have three types of tests:

    Tests that only apply when running outside of a platform (or profile), such as on Java SE, to test behavior defined by the specification for that mode of execution.
    Tests that only apply when running in a platform (or profile) to test behavior defined by the specification for that mode of execution.
    Tests that apply to the behavior defined by the specification for all modes of execution.

The tests of type 2 and 3 must be able to be executed in the context of the profile they are included in: platform, web profile or core profile.

We want to discuss proposing the following requirements for individual specification TCKs within the specification committee:

    The individual specification TCK must provide a profile-ready mechanism for running the required TCK tests (types 2 and 3) in the profiles they are included in: platform, web profile or core profile. Type 1 tests must be excluded and not required to be executed.
    The individual specification TCK must provide a mechanism for running the required TCK tests (types 1 and 3) outside the context of a platform or profile such as on Java SE. Type 2 tests must be excluded and not run.
    It is important that type 3 tests be run in compatible implementations of the profiles to validate the individual specification implementation functions properly in the profile implementation: platform, web profile or core profile.

Note that we avoided using the term "standalone TCK" because to some the term "standalone" means TCKs that run outside of any platform or profile container.

From the email discussion [thread](https://www.eclipse.org/lists/jakarta.ee-spec.committee/msg03112.html)

**Comment by paulbuck** [comment]
Recommendation is to do a PR against the Jakarta EE TCK Process document (https://jakarta.ee/committees/specification/tckprocess/) that describes the requirements for standalone TCKs, in particular those that are derived from the Platform or Web Profile TCKs.

**Comment by Emily-Jiang** [comment]
I suggest to add the following text under the heading:
### 
TCK types and requirements

There are 3 different types of TCKs, detailed below.
Type 1: Tests that only apply when running outside of a platform (or profile), such as on Java SE, to test behavior defined by the specification for that mode of execution.
Type 2: Tests that only apply when running in a platform (or profile) to test behavior defined by the specification for that mode of execution.
Type 3: Tests that apply to the behavior defined by the specification for all modes of execution.

The individual specification TCK must provide a profile-ready mechanism for running the required TCK tests (types 2 and 3) in the profiles they are included in: platform, web profile or core profile. Type 1 tests must be excluded and not required to be executed.
The individual specification TCK must provide a mechanism for running the required TCK tests (types 1 and 3) outside the context of a platform or profile such as on Java SE. Type 2 tests must be excluded and not run.
It is important that type 3 tests be run in compatible implementations of the profiles to validate the individual specification implementation functions properly in the profile implementation: platform, web profile or core profile.
