### ISSUE TITLE
Tracking Issue for rebasing JESP to EFSP 1.3

### ISSUE THREAD

**Issue by ivargrimstad** [jakartaee/specification-committee#60]
Issue in JESP repository: https://github.com/jakartaee/JESP/issues/10
Pull Request with the suggested update: https://github.com/jakartaee/JESP/pull/9

**Comment by paulbuck** [comment]
References ...

JESP 1.3 ([link](https://jakarta.ee/about/jesp/))
EFSP 1.2 ([link](https://www.eclipse.org/projects/efsp/?version=1.2))
EFSP 1.3 ([link](https://www.eclipse.org/projects/efsp/?version=1.3)) ([diff from 1.2](https://www.eclipse.org/projects/efsp/diff.php))

**Comment by edbratt** [comment]
I believe this is resolved. The [latest JESP (1.4) ](https://jakarta.ee/about/jesp/)adops EFSP 1.3.

**Comment by ivargrimstad** [comment]
Yes, good catch @edbratt
