### ISSUE TITLE
JESP/TCK Process needs to be extended to support standalone TCK used in multiple profiles

### ISSUE THREAD

**Issue by starksm64** [jakartaee/specification-committee#61]
A stumbling block we ran into in the EE10 release was component specifications that have newly created standalone TCKs that target more than one profile, but had not validated that they could be run in those different profiles. 

A proper fix most likely entails component specifications separating out TCK tests that rely on specifications outside of the component specification in the form of one or more profile related artifacts that are validated as part of the profile specification release, not the component specification.

**Comment by paulbuck** [comment]
Could be related to #59 ?

**Comment by paulbuck** [comment]
@starksm64 is this related to [#59](https://github.com/jakartaee/specification-committee/issues/59)? What more is needed to address this issue and was this related the Concurency situation in EE10?

**Comment by ivargrimstad** [comment]
Reopen if it still is things remaining
