### ISSUE TITLE
Clarify durations associated with CCRs

### ISSUE THREAD

**Issue by edbratt** [jakartaee/specification-committee#66]
In EE 10, there were at least a couple of CCRs that were created as place-holders, to be filled in as the work evolved. I believe this practice should be allowed but this creates ambiguity with respect to the CCR approval time-frames. It is not especially clear when the CCR issue is finalized -- especially if it is all completed but for the vendor/project specific TCK documentation (TCK Summary).
While we are working on this, we should address the process by which pre-ballot CCRs must follow to ensure, for example, that no changes are made once the specification goes to ballot.

**Comment by edbratt** [comment]
Initial proposal:
CCRs against Final Specifications -- The issue here is, when does the two week lazy-consensus time begin?  I recommend best practice be that the final attestation check-marks not be checked until the requestor confirms that all requirements are met. The 'lazy-timeout' clock does not start until those boxes are checked. Once they are checked, all materials are expected to be complete and there should be no further unsolicited changes made to the CCR -- Any committer team feedback that requests data changes (something missing, incorrect, etc) -- should re-start the lazy timeout period. If the specification has an active reviewer, that committer could proactively complete the request by declaring that is is complete, mark it accepted, and close it. In the case where that does not happen, the lazy-timeout period would start once the reviewer indicates their feedback has been incorporated. I'm not sure how to flag this. Perhaps we can use labels but the application of and removal of labels might be too. onerous and/or obscure. We could just adopt guidance that the lazy-consensus is 14 days after the last comment if no one from the committer team elects to take the CCR to accepted state.

CCRs against proposed final specifications -- I recommend we adopt a process change that requires the ballot proposed CCR be approved by the specification committer team prior to starting the final ballot. (So the process would require an approved CCR, not just a CCR on file). However, there is no Final specification to actually approve the CCR against so, in this case, the CCR should be marked (approved-pending-ballot -- a new label). The committer and vendor teams should be informed that the CCR should be considered frozen at this point and it will be formally approved, if the specification becomes final. The mentor checklist should be updated to include instructions for ensuring that all CCRs in the approved-pending-ballot label state are updated to approved and closed (indicating they are formally and finally approved -- the Mentor may or may not have sufficient permission to change the status of the CCR so I don't think we can ask the Mentor to approve and close any ballot-pending CCRs).

In summery, adopting this would require revisions to the Specification Process Guide and Mentor check-lists. Committer teams will need to be informed of this "new" state -- approved-pending-ballot; Specification mentors will need to add the 'clean-up CCR' item to their Spec. finalization check-list. But I believe this will remove some elements of ambiguity about the current lazy-consensus-timeout period.

**Comment by kazumura** [comment]
+1

When CCR is updated after approved-pending-ballot (for example, because of TCK updated),
you need to remove approved-pending-ballot label, and then, the committers add approved-pending-ballot label again.
