### ISSUE TITLE
Restructure Jakarta security related specifications under the Jakarta Security specification project

### ISSUE THREAD

**Issue by starksm64** [jakartaee/specification-committee#69]
We have 3 specification projects related to security in Jakarta:

https://projects.eclipse.org/projects/ee4j.authentication
https://projects.eclipse.org/projects/ee4j.authorization
https://projects.eclipse.org/projects/ee4j.es

There has been discussion that these should be three specifications under a single specification project under Jakarta Security. 
A request has been sent to the EMO to ask what the procedure for such a restructuring is.

**Comment by paulbuck** [comment]
This proposal is noted is to be worked by the projects with the EMO. The Spec Committee has taken note of this proposal and will watch for any requests regarding this restructuring from the EMO.
