### ISSUE TITLE
Formalize the compatibility requirements for specification projects

### ISSUE THREAD

**Issue by starksm64** [jakartaee/specification-committee#72]
This platform-dev page:
https://jakartaee.github.io/platform/CompatibilityRequirements

regarding questions that were made in the CDI 4.0 release. There was an issue created to update it:
https://github.com/jakartaee/platform/issues/605

but the requirements of specification projects need to be determine by the specification committee and encoded in the JESP. The platform CompatibilityRequirements could continue to provide context and clarifications vis the Q/A section.

**Comment by ivargrimstad** [comment]
Issue created in Platform Project: https://github.com/jakartaee/platform/issues/894

**Comment by paulbuck** [comment]
The Spec Committee decided not to update the JESP but rather to require conformance with Jakarta EE Specification Versioning, Change, and Deprecation Process documented on the Spec Committee's website -  
[ ](https://jakarta.ee/committees/specification/versioning/)
