### ISSUE TITLE
Formalize the Jakarta usage of semantic versioning

### ISSUE THREAD

**Issue by starksm64** [jakartaee/specification-committee#73]
The platform group has been implicitly using [semantic versioning](https://semver.org) for the past couple of platform releases. There are subtleties around what this means for Jakarta in terms of process relating to deprecation and removal of old APIs and specifications that need to be codified in the [JESP](https://jakarta.ee/about/jesp/).

**Comment by stbischof** [comment]
ref: [Semantic Version with bnd -osgi tooling](https://bnd.bndtools.org/chapters/170-versioning.html)

**Comment by Pandrex247** [comment]
https://jakarta.ee/committees/specification/versioning/
