### ISSUE TITLE
Specification projects shifting from EFSL 1.0 to 1.1

### ISSUE THREAD

**Issue by paulbuck** [jakartaee/specification-committee#79]
In the Jakarta EE Specification Committee call on April 3rd it was decided that projects that are using EFSL 1.0 can continue to use it for EE 11, projects that can shift to use EFSL 1.1 for EE 11 are encouraged but not required to do so. They will be required to do so in the future.

The Plan and Release Review checklists are to be updated to verify that specification projects have shifted to 1.1 in the specification document and the Javadoc footer.

**Comment by ivargrimstad** [comment]
Add it to the issue template for next release.
